const cityDistances = [
  { from: "Tu sofá", to: "La nevera", km: 0 },
  { from: "Barcelona", to: "Sitges", km: 30, country: "España" },
  { from: "Barcelona", to: "Mataró", km: 60, country: "España" },
  { from: "Barcelona", to: "Sabadell", km: 90, country: "España" },
  { from: "Barcelona", to: "Tarragona", km: 120, country: "España" },
  { from: "Barcelona", to: "Lleida", km: 150, country: "España" },
  { from: "Barcelona", to: "Girona", km: 180, country: "España" },
  { from: "Barcelona", to: "Zaragoza", km: 210, country: "España" },
  { from: "Barcelona", to: "Huesca", km: 240, country: "España" },
  { from: "Barcelona", to: "Perpiñán", km: 270, country: "Francia" },
  { from: "Barcelona", to: "Andorra la Vella", km: 300, country: "Andorra" },
  { from: "Barcelona", to: "Montpellier", km: 330, country: "Francia" },
  { from: "Barcelona", to: "Valencia", km: 360, country: "España" },
  { from: "Barcelona", to: "Nîmes", km: 390, country: "Francia" },
  { from: "Barcelona", to: "Toulouse", km: 420, country: "Francia" },
  { from: "Barcelona", to: "Aviñón", km: 450, country: "Francia" },
  { from: "Barcelona", to: "Alicante", km: 480, country: "España" },
  { from: "Barcelona", to: "Marsella", km: 510, country: "Francia" },
  { from: "Barcelona", to: "Aix-en-Provence", km: 540, country: "Francia" },
  { from: "Barcelona", to: "Tolón", km: 570, country: "Francia" },
  { from: "Barcelona", to: "Niza", km: 600, country: "Francia" },
  { from: "Barcelona", to: "Madrid", km: 630, country: "España" },
  { from: "Barcelona", to: "Mónaco", km: 660, country: "Mónaco" },
  { from: "Barcelona", to: "Génova", km: 690, country: "Italia" },
  { from: "Barcelona", to: "Turín", km: 720, country: "Italia" },
  { from: "Barcelona", to: "Lyon", km: 750, country: "Francia" },
  { from: "Barcelona", to: "Grenoble", km: 780, country: "Francia" },
  { from: "Barcelona", to: "Milán", km: 810, country: "Italia" },
  { from: "Barcelona", to: "Ginebra", km: 840, country: "Suiza" },
  { from: "Barcelona", to: "Lausana", km: 870, country: "Suiza" },
  { from: "Barcelona", to: "Berna", km: 900, country: "Suiza" },
  { from: "Barcelona", to: "Dijon", km: 930, country: "Francia" },
  { from: "Barcelona", to: "Basilea", km: 960, country: "Suiza" },
  { from: "Barcelona", to: "Estrasburgo", km: 990, country: "Francia" },
  { from: "Barcelona", to: "París", km: 1020, country: "Francia" },
  { from: "Barcelona", to: "Zúrich", km: 1050, country: "Suiza" },
  { from: "Barcelona", to: "Stuttgart", km: 1080, country: "Alemania" },
  { from: "Barcelona", to: "Karlsruhe", km: 1110, country: "Alemania" },
  { from: "Barcelona", to: "Mannheim", km: 1140, country: "Alemania" },
  { from: "Barcelona", to: "Fráncfort", km: 1170, country: "Alemania" },
  { from: "Barcelona", to: "Colonia", km: 1200, country: "Alemania" },
  { from: "Barcelona", to: "Düsseldorf", km: 1230, country: "Alemania" },
  { from: "Barcelona", to: "Bruselas", km: 1260, country: "Bélgica" },
  { from: "Barcelona", to: "Ámsterdam", km: 1290, country: "Países Bajos" },
  { from: "Barcelona", to: "Hamburgo", km: 1320, country: "Alemania" },
  { from: "Barcelona", to: "Varsovia", km: 1350, country: "Polonia" },
];

export const getClosestCityDistance = (km: number) => {
  return cityDistances.reduce((prev, curr) =>
    Math.abs(curr.km - km) < Math.abs(prev.km - km) ? curr : prev
  );
};
